//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "144.0.35+g12f1636+chromium-144.0.7559.262"
#define CEF_VERSION_MAJOR 144
#define CEF_VERSION_MINOR 0
#define CEF_VERSION_PATCH 35
#define CEF_COMMIT_NUMBER 3436
#define CEF_COMMIT_HASH "12f1636e801da935a59650e7f544fcb7ff8b8e8b"
// clang-format on

#endif // CefVersion
